### ISSUE TITLE
SMTP over SSL seems not to work

### ISSUE THREAD

**Issue by MacGritsch** [MailCore/MailCore#11]
I can not connecto to the google-smtp (smtp.gmail.com) on port 465 (as they describe).
The server, port and account inof is correct beacue it works with other mail-clients.

is this a bug or is this a non supported feature?

Gabriel

**Comment by mronge** [comment]
It should work, are you doing this on iOS or on Mac OS X?

**Comment by jils** [comment]
Works for me with this config:

```[mSmtpConnection initWithServer:@"smtp.gmail.com" 
                          username:@"myusername"
                          password:@"mypass" 
                              port:587 
                            useTLS:YES 
                           useAuth:YES];

```
```

**Comment by hoangtuanfithou** [comment]
- (IBAction)connect:(id)sender {
  NSLog(@"Connecting...");
  CTCoreAccount *myAccount =[[CTCoreAccount alloc] init];
  
  [myAccount connectToServer:@"smtp.gmail.com" port:993 connectionType:CONNECTION_TYPE_TLS
                    authType:IMAP_AUTH_TYPE_PLAIN login:@"myacc@gmail.com" password:@"mypassword"];
  
  //[myAccount connectToServer:@"imap.softbank.jp" port:993 connectionType:CONNECTION_TYPE_TLS
    //                  authType:IMAP_AUTH_TYPE_PLAIN login:@"s7umbf5nat" password:@"123456789"];
  
  CTCoreFolder *inbox = [myAccount folderWithPath:@"INBOX"];
  NSLog(@"INBOX %@", inbox);
  // set the toIndex to 0 so all messages are loaded
  NSSet *messageSet = [inbox messageObjectsFromIndex:2 toIndex:5]; 
  
  NSEnumerator *objEnum = [messageSet objectEnumerator];
  id msg;
  
  while(msg = [objEnum nextObject]) {
           NSLog(@"Subject : %@", [msg subject]);
  }

}

---

Hi !
I use above code
- It work on Gmail
- And can not work on Softbank Mail 
1. (port is right, cause i take it from old version)
2. try both with s7umbf5nat and s7umbf5nat@i.softbank.jp
3. pass is right, cause i test with old version and it working
4. When Debug is crash on connectToServer-> ...-> libetpan...

anyone know ? pls help

**Comment by MacGritsch** [comment]
Hi,

I mean SSL on Port 465 - not AUTHTLS on port 587!

**Comment by mronge** [comment]
MailCore only supports STARTTLS right now for SMTP

**Comment by mronge** [comment]
TLS is now supported:

I've changed the method for sending message:

   BOOL success = [CTSMTPConnection sendMessage:testMsg 
                                                                        server:@"mail.test.com"
                                                                   username:@"test"
                                                                    password:@"test"
                                                                            port:587
                                                           connectionType:CTSMTPConnectionTypeStartTLS
                                                                      useAuth:YES
                                                                            error:&error];

you'll need to use the port 465 and CTSMTPConnectionTypeTLS as the connectionType
