### ISSUE TITLE
How long can I cache CTCoreAccount ?

### ISSUE THREAD

**Issue by abhinavguptas** [MailCore/MailCore#116]
Connecting to server using CTCoreAccount takes some time, so for better response I am trying to cache the CTCoreAccount. Though I ran into some issues, which seems to be disconnection from server. 

I checked the methods like CTCoreAccount:isConnected etc, but they are not working correctly, as the "connected" attribute only gets set to "NO", if disconnect is called.

**Comment by mronge** [comment]
Is this on the Mac or iOS?

On iOS I listen for a network reachability changes and disconnect the connection when I see the network change. This way I am often using a fresh connection which is much faster than trying to reuse an old one.

**Comment by abhinavguptas** [comment]
Great tip @mronge - thanks !
