### ISSUE TITLE
MailCore iOS: How to retrieve attachments from mail?

### ISSUE THREAD

**Issue by Pankaj03** [MailCore/MailCore#118]
Hello,

I am using MailCore Api in my application. I get the mail from inbox, but i didn't find any solution to get attachments. See my code stuff as : 

CTCoreFolder *inbox = [account folderWithPath:@"INBOX"];
    NSArray *msgArr1 = [inbox messagesFromSequenceNumber:1 to:0 withFetchAttributes:CTFetchAttrEnvelope | CTFetchAttrBodyStructure];

```
NSMutableArray *messages = [NSMutableArray arrayWithArray:msgArr1];
```

 if ([messages count] > 0) {  
        for (int i = 0; i< [messages count]; i++) {

```
        CTCoreMessage *msg = [messages objectAtIndex:i];
        Message *msgObj = [[Message alloc] init];
        BOOL isHTML;
        msgObj.msgBody = [msg bodyPreferringPlainText:&isHTML];
        msgObj.msgSub = [msg subject];
        msgObj.msgDateTime = [msg senderDate];
        msgObj.msgAttachments = [msg.attachments copy];
        msgObj.msgFrom = [NSString stringWithString:newMsgFrom];
        [listOfItems addObject:msgObj];

    }
}
```

How can i get attachments in NSData to download/show?

Anyone please help me, i am new to ios development!
My xcode version is 4.6.3 and ios 6.1.

**Comment by nidhisingla** [comment]
HI, Anyone plz help in downloading the attachment using the mailcore2 example.

**Comment by Pankaj03** [comment]
@nidhisingla  Provide some code and description of error you getting.

**Comment by nidhisingla** [comment]
Hi Pankaj, Thanks for replying on my query. However i m not getting any error but the issue is that an image of the attachment is displayed but whenever i clicked / long pressed its not opening. I m able to get the attachment file name but do not know the method how to open that attachment. Below is the code where m getting the message and the name of the file :+1: - 

(void) setMessage:(MCOIMAPMessage *)message
{
    MCLog("set message : %s", message.description.UTF8String);

```
for(MCOOperation * op in _ops) {
    [op cancel];
}
[_ops removeAllObjects];

[_callbacks removeAllObjects];
[_pending removeAllObjects];
[_storage removeAllObjects];
_message = message;
NSLog(@"\n\n*********folder :%@**uid : %d",_folder,[_message uid]);
```

   // NSLog(@"**********%@",[_message attachments]);
    NSArray *msg_attachment = [_message attachments];
    NSData *attachment_data = [msg_attachment valueForKey:@"Attachment"];
    NSLog(@"%@",[msg_attachment valueForKey:@"filename"]);

}

Also want to know how we can implement IMAP with OMTP protocol as the mailcore is on the base of IMAP and SMTP. Thanks a lot for helping me out.

**Comment by Pankaj03** [comment]
@nidhisingla 

 Hello,
U have to download the attachement first.

In my case, i had download the attachment to documents folder of application, and show it in webview by giving a documents folder path. See the below code snippet to download the attachement and save it to documents folder:

```
MCOIMAPMessage *msgImap = [_msgArray objectAtIndex:0];

if ([msgImap.attachments count] > 0) {

        for (int k = 0; k < [msgImap.attachments count]; k++) {
MCOIMAPPart *part = [msgImap.attachments objectAtIndex:k];
MCOIMAPFetchContentOperation *mcop = [self.appImapSession fetchMessageAttachmentByUIDOperationWithFolder:@"INBOX" uid:msgImap.uid partID:part.partID encoding:part.encoding];
 [mcop start:^(NSError *error, NSData *data) {        
            if (error != nil) {
                NSLog(@"error:%@", error);
                return;
            }
            NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
            NSString *saveDirectory = [paths objectAtIndex:0];
            NSString *attachmentPath = [saveDirectory stringByAppendingPathComponent:part.filename];             
            BOOL fileExists = [[NSFileManager defaultManager] fileExistsAtPath:attachmentPath];
            if (fileExists) {
                NSLog(@"File already exists!");
            }
            else{
               [data writeToFile:attachmentPath atomically:YES];
            }
        }];
}
}
```

Further, u want to implement the IMAP and SMTP, read this doc and examples:
http://libmailcore.com/

**Comment by nidhisingla** [comment]
Thanks Pankaj, will try using the method and hope you will not mind if i bother you again. Also plz confirm whether the same method described above can be used for downloading the sound files and how to play them back. 

Adding to this i want to implement the IMAP and OMTP. Plz help in this as well. Thanks again.

**Comment by nidhisingla** [comment]
Thanks Pankaj, for your wonderful support. I m now able to download the attachment in the document folder of the application. The only issue left is as below:
1. TXT file which i had downloaded from the mail include the entire email as well and content of file is displayed as a part of email message. I want that the txt file should contain only the data.
3. How to show this TXT file within my app
2. I want to save the sound files which can then be played back through code.

I hope you will help me out in this as my main purpose is to download the sound files basically phone recordings and then play them back in the application.

Code which was successfully run for downloading is as below 

MCOIMAPFetchContentOperation \* op = [_session fetchMessageByUIDOperationWithFolder:_folder uid:[_message uid]];
        [_ops addObject:op];
        [op start:^(NSError \* error, NSData \* data) {
            NSLog(@"******\* here in op start");
            if ([error code] != MCOErrorNone) {
                return;
            }
            NSLog(@"******\* here in after error code check");
            NSAssert(data != nil, @"data != nil");

```
        MCOMessageParser * msg = [MCOMessageParser messageParserWithData:data];
        [_messageView setDelegate:self];
        [_messageView setFolder:_folder];
        [_messageView setMessage:msg];
        NSLog(@"%@",msg);

        //below code by nidhi for downloading
        if ([_message.attachments count] > 0)
        {
        MCOIMAPPart *part = [_message.attachments objectAtIndex:0];
        NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
        NSString *saveDirectory = [paths objectAtIndex:0];
        NSString *attachmentPath = [saveDirectory stringByAppendingPathComponent:part.filename];
        BOOL fileExists = [[NSFileManager defaultManager] fileExistsAtPath:attachmentPath];
        if (fileExists) {
            NSLog(@"File already exists!");
        }
        else{
            [data writeToFile:attachmentPath atomically:YES];
        }
        }
    }];
```

**Comment by Pankaj03** [comment]
@nidhisingla  You can use UIWebview within application to show your text file and play your audio files. In webview you can pass the file path of document folder.

N

Enjoy!

**Comment by nidhisingla** [comment]
Hi pankaj,

plz help in implementing the IMap with OMTP protocol. this is required in getting the voice mails from the server so that the use can listen it later. this is somewhat urgent as already wasted 20-30 days on this.

Thanks

**Comment by dresetnic** [comment]
Hello @nidhisingla , Pankaj, 
I want to implement the IMAP with OMTP. I have a voicemail server and I need to get the voice mails so that the user can listen to it later.
 Can you show some sample code or suggest some way for doing that?
Thanks
