### ISSUE TITLE
Problem with CTCoreMessage -buildUpHtmlBodyText:result:

### ISSUE THREAD

**Issue by siberianisaev** [MailCore/MailCore#124]
Hello! I'm experiencing a series of crashes in my mail app that uses MailCore.
Any suggestions?

Stack trace 1:

Hardware Model:      iPhone4,1
Process:         My App Name [36932]
Code Type:       ARM
Parent Process:  launchd [1]

Exception Type:  SIGSEGV
Exception Codes: SEGV_ACCERR at 0x5204777b
Crashed Thread:  14

Thread 14 Crashed:
0   My App Name               0x001d79f8 -[CTMIME_SinglePart fetchPartWithProgress:] + 167
1   My App Name               0x001d7b07 -[CTMIME_SinglePart fetchPart] + 30
2   My App Name               0x001db9b9 -[CTCoreMessage _buildUpHtmlBodyText:result:] + 404
3   My App Name               0x001db995 -[CTCoreMessage _buildUpHtmlBodyText:result:] + 368
4   My App Name               0x001db89d -[CTCoreMessage _buildUpHtmlBodyText:result:] + 120
5   My App Name               0x001db5f1 -[CTCoreMessage htmlBody] + 120
6   My App Name               0x00117427 -[MANConnection operationFetchBody:folder:completeBlock:] + 1074
7   My App Name               0x0014bc2b -[MANOperation main] + 74
8   Foundation                    0x332175c1 0x331f0000 + 161217
9   Foundation                    0x3328fbe3 0x331f0000 + 654307
10  libdispatch.dylib            0x3aaca11f 0x3aac8000 + 8479
11  libdispatch.dylib            0x3aace961 -[OS_object _dispose] + 11692
12  libdispatch.dylib            0x3aaceac1 -[OS_object _dispose] + 12044
13  libsystem_c.dylib          0x3aafea11 0x3aaf8000 + 27153

Stack trace 2:

Hardware Model:      iPhone5,2
Code Type:       ARM
Parent Process:  launchd [1]
Exception Type:  SIGSEGV
Exception Codes: SEGV_ACCERR at 0x50
Crashed Thread:  18

Thread 18 Crashed:
0   My App Name               0x0014c864 -[CTMIME_HtmlPart buildMIMEStruct] + 40555
1   My App Name               0x0013bf63 -[CTMIME_SinglePart fetchPart] + 30
2   My App Name               0x0013fe01 -[CTCoreMessage _buildUpHtmlBodyText:result:] + 404
3   My App Name               0x0013fce5 -[CTCoreMessage _buildUpHtmlBodyText:result:] + 120
4   My App Name               0x0013fa39 -[CTCoreMessage htmlBody] + 120
5   My App Name               0x0007bb2f -[MANConnection operationFetchBody:folder:completeBlock:] + 1074
6   My App Name               0x000b0279 -[MANOperation main] + 72
7   Foundation                    0x348d6a89 -[__NSOperationInternal start] + 840
8   Foundation                    0x3494efe7 -[NSOperationQueue __] + 2854
9   libdispatch.dylib             0x3c15d793 0x3c15c000 + 6035
10  libdispatch.dylib            0x3c161657 -[OS_object _dispose] + 13618
11  libdispatch.dylib            0x3c1617d9 -[OS_object _dispose] + 14004
12  libsystem_c.dylib          0x3c1857f1 0x3c17f000 + 26609

Stack trace 3

Hardware Model:      iPhone5,1
Code Type:       ARM
Parent Process:  launchd [1]
Exception Type:  SIGSEGV
Exception Codes: SEGV_ACCERR at 0xf0000000
Crashed Thread:  13

Thread 13 Crashed:
0   My App Name                          0x001f8eb8 -[CTCoreMessage setParentFolder:] + 117843
1   My App Name                          0x001f8fdf -[CTCoreMessage setParentFolder:] + 118138
2   My App Name                         0x001d6def -[CTMIME_SinglePart fetchPartWithProgress:] + 66
3   My App Name                          0x001d6f63 -[CTMIME_SinglePart fetchPart] + 30
4   My App Name                          0x001dac2d -[CTCoreMessage _buildUpBodyText:result:] + 404
5   My App Name                          0x001dac09 -[CTCoreMessage _buildUpBodyText:result:] + 368
6   My App Name                          0x001dab11 -[CTCoreMessage _buildUpBodyText:result:] + 120
7   My App Name                          0x001da86d -[CTCoreMessage body] + 120
8   My App Name                          0x00116b53 -[MANConnection operationFetchBody:folder:completeBlock:] + 1110
9   My App Name                          0x0014b279 -[MANOperation main] + 72
10  Foundation                          0x3339ca89 -[__NSOperationInternal start] + 840
11  Foundation                          0x33414fe7 -[NSOperationQueue __] + 2854
12  libdispatch.dylib                   0x3ac23793 0x3ac22000 + 6035
13  libdispatch.dylib                   0x3ac27657 -[OS_object _dispose] + 13618
14  libdispatch.dylib                   0x3ac277d9 -[OS_object _dispose] + 14004
15  libsystem_c.dylib                   0x3ac4b7f1 0x3ac45000 + 26609

Thanks!

**Comment by sandypc** [comment]
The problem may be due to , memory leaks , kindly fix the memory leaks in Mailcore and use new libetpan then check.

**Comment by siberianisaev** [comment]
The bug was fixed after migrating to ARC in project and library update.
