### ISSUE TITLE
Put the LICENSE file to the source root

### ISSUE THREAD

**Issue by dmitriy-kiriyenko** [MailCore/MailCore#15]
If you don't care of licensing - put the [MIT license](http://en.wikipedia.org/wiki/MIT_License). It's the best for this.

**Comment by dmitriy-kiriyenko** [comment]
I can make a PR if you wish, but such a PR would look a little odd for me =)

**Comment by mronge** [comment]
It is currently BSD licensed, I'll put that in LICENSE

**Comment by mronge** [comment]
Added a LICENSE file to 1.0-beta which will be merged until master once it is stable
