### ISSUE TITLE
Header Search Paths

### ISSUE THREAD

**Issue by skurfer** [MailCore/MailCore#19]
I’m pretty good with Objective-C, but not so good with Xcode, so forgive me if I’m missing something stupid…

If I clone the MailCore repo and follow the instructions to add it to my project, MailCore builds fine, but my project fails at the end claiming that it can’t locate `MailCore/MailCore.h`. If I add both `MailCore/Source` and `MailCore/libetpan/build-mac/include` to Header Search Paths, it will build (assuming I also change the line to `#import "MailCore.h"`).

The instructions used to include adding `../MailCore/include` to Header Search Paths. I’m guessing 704741e85bfbfa92d1a20dba0387013c20cbad4b was supposed to make that unnecessary? But for me, it isn’t. For what it’s worth, I had to add the entry for `libtpan` _before_ the recent commit as well.

Thanks.

**Comment by jwilling** [comment]
Is this for an iOS project, or for Mac? There's no need now for header search paths on the Mac at all, whereas on iOS you have to use MailCore via a static lib which requires header search paths.

**Comment by skurfer** [comment]
> Is this for an iOS project, or for Mac?

Sorry… Mac. Specifically, in [my fork](https://github.com/skurfer/elements.support.mail-qsplugin) of Quicksilver’s E-mail Support plug-in.

> There's no need now for header search paths on the Mac at all

Well that’s the impression I got, which is why I ask, because I seem to need them. :-) Could the Framework Search Paths be interfering? (I notice it’s blank by default in a new project, but it’s not blank for Quicksilver plug-ins.)

**Comment by mronge** [comment]
Did you add MailCore as a sub-project in your Xcode project?

**Comment by skurfer** [comment]
Yes, and MailCore itself appears to build (from within my project) without issue. I did everything mentioned at http://libmailcore.com/#macadding And for what it’s worth, when I _do_ add the Header Search Paths to make it build, the resulting plug-in contains the framework (from the copy phase), so I’m pretty sure the rest is set up correctly.

**Edit:** Oh, and I can send mail through my SMTP server. That’s another major clue that it’s getting built and copied into the plug-in. ;-)

**Comment by mronge** [comment]
Huh, that is a head scratcher... not sure what is going on

**Comment by skurfer** [comment]
Well, it’s not the end of the world if I have to include the extra build setting. I just wanted to avoid it if possible and wondered what I was doing wrong. Thanks.

**Comment by gsboris** [comment]
lexical or preprocessor issue: MailCore/MailCore.h file not found, any help?

**Comment by mronge** [comment]
Hi!

Did you double check that you have "$(BUILT_PRODUCTS_DIR)/../../include" added to Header Search Paths on your project?

Also is this for Mac or iOS?

**Comment by gsboris** [comment]
Hi Matt, ty for quick reply. Yes I checked it many times, reinstalled it several times, nothing helped. The only way I was able to make it to work was using:
#import "MailCore.h"
not #iimport '<'MailCore/MailCore.h'>'

Do you have any idea why this could happen?
Tx

**Comment by dermotos** [comment]
I have the same issue, but I got it building by specifying #import "MailCore/Source/MailCore.h"
I haven't yet tested this, but it builds.
