### ISSUE TITLE
fatal error and Unable to checkout.

### ISSUE THREAD

**Issue by Loneless** [MailCore/MailCore#21]
When try "git submodule update --init" command.

Terminal log.
Submodule 'iOSPorts' (https://github.com/mronge/iOSPorts.git) registered for path 'iOSPorts'
Submodule 'libetpan' (https://github.com/mronge/libetpan.git) registered for path 'libetpan'
Cloning into 'iOSPorts'...
remote: Counting objects: 2024, done.
remote: Compressing objects: 100% (975/975), done.
remote: Total 2024 (delta 1058), reused 1706 (delta 820)
Receiving objects: 100% (2024/2024), 1.19 MiB | 396 KiB/s, done.
Resolving deltas: 100% (1058/1058), done.
fatal: reference is not a tree: ec41248411126096584f0afd34f2b1844f51bca7
Cloning into 'libetpan'...
remote: Counting objects: 1025, done.
remote: Compressing objects: 100% (412/412), done.
remote: Total 1025 (delta 644), reused 969 (delta 597)
Receiving objects: 100% (1025/1025), 1.06 MiB | 559 KiB/s, done.
Resolving deltas: 100% (644/644), done.
Submodule path 'libetpan': checked out 'ed9109b1d4928cc9067fbcf375b3b0f8420b3e9a'
Unable to checkout 'ec41248411126096584f0afd34f2b1844f51bca7' in submodule path 'iOSPorts'

How can i fix it? Help me.

**Comment by mronge** [comment]
I forgot to push a commit, it should work now :)
