### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by JanC** [MailCore/MailCore#27]
Hi,
I see that there are some memory leaks if I just use the sample code from the Gettings Started.

![Screenshot](http://f.cl.ly/items/1s0w2L0R1u3T460E3v42/Screen%20Shot%202012-08-16%20at%2011.10.00%20AM.png)

In the render method, the  _mailmime_ returned from _buildMIMEStruct_ is never freed.

![Screenshot](http://f.cl.ly/items/171233343u1k0q2n0x2E/Screen%20Shot%202012-08-16%20at%2011.11.32%20AM.png)

**Comment by avaidyam** [comment]
Simple fix: move the `[self buildMIMEStruct]` outside the `mailmime_write_mem()` call, and assign it to a variable. Then free the variable after the `mailmime_write_mem()` call.

**Comment by mronge** [comment]
Fixed, thanks!

**Comment by avaidyam** [comment]
This doesn't fit in the scope of the issue, but does the x-gm-labels extension work? And if so, how can I use it?

**Comment by mronge** [comment]
I know it does, but I have not used it myself

**Comment by avaidyam** [comment]
Alright, thanks!

**Comment by ovidiusabou** [comment]
And now it frees a string that it shouldn't: the filename of an attachment (mFilename in MIME_SinglePart).

This patch seems to fix the crash.

```
index 0e5f424..e69b8d3 100644
--- a/Source/CTMIME_SinglePart.m
+++ b/Source/CTMIME_SinglePart.m
@@ -201,8 +201,11 @@ static void download_progress_callback(size_t current, size_t maximum, void * co
     int r;

     if (mFilename) {
+        char *charData = (char *)[mFilename cStringUsingEncoding:NSUTF8StringEncoding];
+        char *dupeData = malloc(strlen(charData));
+        strcpy(dupeData, charData);
         mime_fields = mailmime_fields_new_filename( MAILMIME_DISPOSITION_TYPE_ATTACHMENT, 
-                                                    (char *)[mFilename cStringUsingEncoding:NSUTF8StringEncoding], 
+                                                    dupeData,
                                                     MAILMIME_MECHANISM_BASE64 ); 
     } else {
         mime_fields = mailmime_fields_new_encoding(MAILMIME_MECHANISM_BASE64);
```

**Comment by mronge** [comment]
## Thanks, your patch has been committed

Matt Ronge

iOS Developer & Consultant
Central Atomics Inc.
http://www.centralatomics.com
