### ISSUE TITLE
No concurrency support?

### ISSUE THREAD

**Issue by honcheng** [MailCore/MailCore#29]
Is it a limitation of MailCore or IMAP, that all requests to server must be done in a single queue? 
If I have more than one concurrent requests, it will either crash the app or returns nothing. Maybe I missed out on some settings to enable concurrency?

**Comment by bparousis** [comment]
I use dispatch_async to make asynchronous requests.

**Comment by honcheng** [comment]
I do too, but it'll crash. Let's say I have 10 emails and I retrieve all bodies of the 10 emails in 10 async queues. That will crash the app. I have to use an NSOperarionQueue with max 1 concurrent async request so that it doesn't crash the app

**Comment by bparousis** [comment]
Oh, I see.  So you're fetching individual emails asynchronously.  Okay, I was just calling "[folder messagesFromSequenceNumber:1 to:0 withFetchAttributes:CTFetchAttrEnvelope];" from within my async block.

**Comment by jwilling** [comment]
I've experienced crashes as well when trying to asynchronously retrieve the message bodies. What I've resorted to is popping the message body fetch to _another_ async queue, and updating the UI on the main thread after each body has been fetched. Doesn't appear to be too slow.

**Comment by bparousis** [comment]
Is this happening with gmail?  It's probably because you're exceeding the maximum of 10 connections.

http://support.google.com/mail/bin/answer.py?hl=en&answer=97150

**Comment by honcheng** [comment]
@Digity I'm only using 1 connection, more than that and it crashes. I'm using messagesFromSequenceNumber:to:withFetchAttributes: to fetch emails as well. If I'm trying to load body, then call this method simultaneously, I may not get any response. 

@jwilling what is the maximum concurrent requests you set for your async queue? I can only use 1.

**Comment by jwilling** [comment]
@honcheng Actually what I meant is that when I dispatch in a new queue to get the message bodies, I'm doing so in a loop, so effectively I'm only having one concurrent body fetch.

**Comment by honcheng** [comment]
@jwilling  ah ok. When I do it in a single queue, it probably has the same effect? So there's no solution to enable concurrency? 

What I've resorted to do is to have just a single queue, and set queue priority for operations. For example, if there are still 10 HTMLbody loading queues, and I'm trying to offset and load more emails, email loading will have higher priority than htmlbody loading so it doesn't feel slow. That's just a workaround.

**Comment by jwilling** [comment]
@honcheng Can't say it's the best way, but I just simply grab the envelope first, and display those. As soon as the email attributes are fetched, **then** the message bodies are fetched on another thread like I said before.

So to the user, it has the appearance of an almost instantaneous reload, then the message previews start flying in as soon as they become available.

**Comment by mronge** [comment]
You can have multiple requests but each thread needs its own CTCoreAccount and CTCoreFolder, they CANNOT be shared across threads.

**Comment by honcheng** [comment]
thanks.

**Comment by aaaaahaaaaa** [comment]
Threads on iOS are supposed to have shared memory. I don't exactly understand why reusing the same CTCoreAccount across threads doesn't work, even if references are used in the LibetPan library.

@mronge Can I ask you how you would do this ? How to define a unique CTCoreAccount or CTCoreFolder "attached" to a different thread or queue that can be reused multiple times.
What I mean is, I want a new thread or queue to handle all the requests to the server, pushing informations to the main queue for UI updates. And without having to define a new CTCoreAccount each time I'm using this other thread.

I know this more of a general dev question, but I thought it would be more efficient to ask it here.

**Comment by mronge** [comment]
One way is to create an object that contains both the NSOperationQueue (with the maxConcurrentOperationCount=1) and the CTCoreAccount. All work for that account goes through the object, and is only executed on one thread at a time. Then you can one of these objects for each account you want to access.

Hope that helps,

**Comment by aaaaahaaaaa** [comment]
Thanks !
