### ISSUE TITLE
"[GMail]" folder causes exception

### ISSUE THREAD

**Issue by tcurdt** [MailCore/MailCore#3]
Connecting to Google's IMAP and going through the folder (see https://github.com/mronge/MailCore/issues/2) ...getting the total message counts throws an exception for the "[GMail]" folder.

I assume this one is special as it's the parent of some other folders. Maybe just something to check in the metadata somewhere ...but haven't found that yet.

**Comment by sarahhodne** [comment]
I don't think the [GMail] folder is an actual folder. It's more like a "namespace".

**Comment by tcurdt** [comment]
But how do you know a certain folder is a namespace?

**Comment by mronge** [comment]
I changed MailCore so "namespaces" like [GMail] are no longer returned as part of folder list
