### ISSUE TITLE
can not compile on mac 10.8 with xcode 4.4

### ISSUE THREAD

**Issue by wangmxf** [MailCore/MailCore#35]
it related libetpan

**Comment by jwilling** [comment]
Does it show any warnings or build errors? Would you be able to either list those here, or take a screenshot?

**Comment by toddfreese** [comment]
Make sure you have the Xcode command line tools installed. It is required for libetpan.

**Comment by andrewzimmer906** [comment]
I believe I'm having the same issue.  The error is 'config.h' file not found.

Here is a screenshot: http://www.flickr.com/photos/69383241@N06/7938528682/in/photostream/

Also, I just updated my XCode command line tools to the latest version in the downloads section of xcode preferences.

**Comment by mronge** [comment]
Make sure you don't have any spaces in the path leading to your project folder. For some reason LibEtPan can't handle spaces in the path name (bug in in the config somewhere I'm sure)

**Comment by andrewzimmer906** [comment]
Oh right. _smacks head_ That's what it was.
Thanks!
