### ISSUE TITLE
The fetched HTML email without <html>, <head> and <body>  tags

### ISSUE THREAD

**Issue by voicecho** [MailCore/MailCore#38]
In the CTCoreMessage.m class

-(void)_buildUpHtmlBodyText:(CTMIME *)mime result:(NSMutableString *)result{
...
}

the result did not have any  <html>, <head> and <body>  tags in it. That's why? How could I get the width information of the HTML web page?

**Comment by mronge** [comment]
That method returns any HTML contents it finds in the message body. Determining what width the HTML content should be when displayed is outside the scope of MailCore
