### ISSUE TITLE
CTCoreAccount:read questions

### ISSUE THREAD

**Issue by troystribling** [MailCore/MailCore#39]
I have been trying to use CTCoreAccount:read. It always seems to timeout and return NULL and the lastError on the account is also NULL. There is not much information on how it should be used.

Has anyone had any luck with it?

**Comment by jwilling** [comment]
Are you sure that the account you're trying to use supports IDLE? Otherwise the method will not accomplish what you're hoping for.

**Comment by troystribling** [comment]
I did not understand IDLE. I have it working now using,

```
[account idle];
NSString* result = [account read];
[account done];
```

Thanks
