### ISSUE TITLE
Is it possible to get the progress of send an email with mailcore?

### ISSUE THREAD

**Issue by voicecho** [MailCore/MailCore#40]
Im using the following method to send an email. Is it possible to get the percentage of email which has been send? I need the progress to feed my progress bar. Thanks in advance!
- (BOOL)sendMessage:(CTCoreMessage *)message server:(NSString *)server username:(NSString *)username

**Comment by mronge** [comment]
It is possible to do but not currently implemented. LibEtPan supports getting the progress of the e-mail, take a look at CTMIME_SinglePart.h and how it handles progress. There should be similar functions in LibEtPan for SMTP

Hope that helps.

Patches welcome!

**Comment by voicecho** [comment]
I got the progress in mail stream_helper.c, but i how could i post a notification in the .c code?  Details plz check the following link: http://stackoverflow.com/questions/12419161/post-a-notification-in-c-file

**Comment by rahulvyas** [comment]
First import this header in your header file. This is already available in mail core 

#import "CTSMTPAsyncConnection.h"

Use this method to send mail

//Note - self.currentServerSettings is a data modal which holds all the required info to send mail.
// self.myMessage is CTCoreMessage object.

CTSMTPAsyncConnection *connection = [[[CTSMTPAsyncConnection alloc] initWithServer:self.currentServerSettings.outgoingAddress
                                                                                      username:self.currentServerSettings.userEmail
                                                                                      password:self.currentServerSettings.userPassword 
                                                                                          port:self.currentServerSettings.outgoingPort
                                                                                        useTLS:(self.currentServerSettings.smtpTLS == 0)?YES:NO
                                                                                       useAuth:(self.currentServerSettings.smtpAuth == 0)?YES:NO
                                                                                      delegate:self] autorelease];
            [connection sendMessageInBackgroundAndNotify:self.myMessage];   

you will receive delegate callbacks in these two methods

//This is called with values between 0-100 (inclusive)
- (void)smtpProgress:(unsigned int)aProgress {

}
- (void)smtpDidFinishSendingMessage:(CTSMTPAsyncStatus)aStatus {
  
  switch (aStatus) {
      case CTSMTPAsyncSuccess:
  
  ```
      break;
  case CTSMTPAsyncCanceled:
      break;
  case CTSMTPAsyncError:
      break;
  default:
      break;
  ```
  
  }
  }
