### ISSUE TITLE
XCode GM build issues (armv7s arch)

### ISSUE THREAD

**Issue by JanC** [MailCore/MailCore#41]
Hi,
I've just downloaded XCode 4.5 GM but my MailCore project does not build. I get those warnings:

```
Ignoring file libsasl2.a, file was built for archive which is not the architecture being linked (armv7s): 
```

Same for libmailcore, libcrypto, libssl.

I think all the libs need be changed to build to the "default" architecture $(ARCHS_STANDARD_32_BIT) which is now armv7 and armv7s 

In libcrypto, and libssl,  I had to add "armv7s" in the "Valid Architectures"

This removes the warnings, and all libs seem to build for armv7 and armv7s but I'm still getting linker errors 

![](http://f.cl.ly/items/0B033T3Y1j290N2K3m1O/Screen%20Shot%202012-09-14%20at%2010.41.38%20AM.png)

**Comment by mronge** [comment]
This should be fixed, just pushed a commit
