### ISSUE TITLE
messageObjectsFromIndex gives unexpected results

### ISSUE THREAD

**Issue by tcurdt** [MailCore/MailCore#5]
Do I just have wrong expectations?

I have cases where the number of messages returned does not match the index range:

```
NSSet *messages1 = [folder messageObjectsFromIndex:0 toIndex:100-1];
NSSet *messages2 = [folder messageObjectsFromIndex:100 toIndex:200-1];
NSSet *messages3 = [folder messageObjectsFromIndex:200 toIndex:300-1];
[messages1 count] == 156
[messages1 count] == 100
[messages1 count] == 55
```

Here are a couple of examples:

```
 folder1:
  0..35: 2
 folder2:
  0..100: 157
  100..200: 100
  200..255: 55
 folder3:
  0..100: 3499
  100..200: 100
  200..300: 100
  300..400: 100
  400..500: 100
```

What's going on there?
Seems like the docs are not up-to-date.

```
/*
    Implementation is in alpha.
*/
//TODO Document Me!
- (NSSet *)messageObjectsFromIndex:(unsigned int)start toIndex:(unsigned int)end;

/*!
    @abstract   This will return the message from this folder with the UID that was passed in. If the message
                can't be found, nil is returned
    @param      uid The uid as an NSString for the message to retrieve.
    @result     A CTMessage object is returned which can be used to get further information and perform operations
                on the message.
*/
```

**Comment by scottgreiff** [comment]
I wish I had a solution, but I've also encountered this problem.  For now I'm just pulling the list of UIDs from messageListWithFetchAttributes and pulling messages using those UIDs... Terribly inefficient, but what can you do if you can't rely on messageObjectsFromIndex?

**Comment by mronge** [comment]
Hi, I've updated the API there are two methods to choose from now:

```
- (NSArray *)messagesFromSequenceNumber:(NSUInteger)startNum to:(NSUInteger)endNum withFetchAttributes:(CTFetchAttributes)attrs
```

and

```
- (NSArray *)messagesFromUID:(NSUInteger)startUID to:(NSUInteger)endUID withFetchAttributes:(CTFetchAttributes)attrs
```

Take a look at the docs to get an idea of what they can do: http://libmailcore.com/api/Classes/CTCoreFolder.html

Also regarding the messages you are getting back not being in the right range, that is very unexpected. What server was that with?

**Comment by tcurdt** [comment]
That was gmail.

**Comment by mronge** [comment]
Next time you see that weird behavior try adding:

   MailCoreEnableLogging()

before you connect. It will dump out the IMAP connection to the console. So then we can see exactly what the client sent and what the server responded with.

If you get a log, please e-mail it to me
