### ISSUE TITLE
Package MailCore as a framework?

### ISSUE THREAD

**Issue by bparousis** [MailCore/MailCore#51]
Is it possible that MailCore could be packaged as a framework and added to a project that way rather than doing the sub-project thing?  I'd want a "MailCore.framework" file that could be added to my project.

**Comment by mronge** [comment]
I used to do this, but got away from it a few years ago. Perhaps once the framework stabilizes and hits 1.0 I'll do it again?

I'm taking a look at CocoaPods http://cocoapods.org/ would that be something helpful?

**Comment by bparousis** [comment]
Yeah, would be nice to have it packaged up as a framework.

I didn't know about CocoaPods, but it seems like it would be pretty helpful.  Right now, I've run into a few issues having MailCore as a subproject...nothing major, but just some obvious nuisances that come up.  I think CocoaPods would be a good solution in the meantime.
