### ISSUE TITLE
Large Attachments

### ISSUE THREAD

**Issue by tgates** [MailCore/MailCore#54]
i"m having a issue fetching large attachments (~8-10mb+). Upon fetching the full attachment, a "Copy command error" is returned. The log shows it connects fine, downloads a small portion of the attachment, and then stops. Has anything experienced a issue like this?

**Comment by mronge** [comment]
Does this happen on both the Simulator and the Device?

**Comment by tgates** [comment]
This is happening on a Mac app, not iOS.

**Comment by tgates** [comment]
Also, when calling rfc822 on a message with a large attachment, nil is returned and "Memory Error" is the last error.

**Comment by tgates** [comment]
Finally figured out the issue that was causing this error. Libetpan was trying to write to /tmp which was denied since my app is conforming to App Sandboxing. Setting the tmpdir for libetpan to one approved by the sandbox fixed this issue.
