### ISSUE TITLE
Invalid username or password

### ISSUE THREAD

**Issue by nyekimov** [MailCore/MailCore#55]
When I try to connect to imap with invalid password, system returns right lastError 'Invalid username or password', but than application fails

LIBETPAN_EXPORT
int mailimap_list(mailimap \* session, const char \* mb,
           const char \* list_mb, clist *\* result)
{
  struct mailimap_response \* response;
  int r;
  int error_code;

  if ((session->imap_state != MAILIMAP_STATE_AUTHENTICATED) &&  <-- EXC_BAD_ACCESS

**Comment by mronge** [comment]
Can you provide some more information on how to reproduce this?

Perhaps are you trying to issue an IMAP command by accident after you've received an auth error?

**Comment by nyekimov** [comment]
Actually you are right. I was continue the work after getting error.
