### ISSUE TITLE
SMTP with Yahoo mail does not work

### ISSUE THREAD

**Issue by honcheng** [MailCore/MailCore#56]
SMTP with Yahoo doesn't seem to work. I used the following configuration

[CTSMTPConnection initWithServer:@"smtp.mail.yahoo.com" 
username:@"myusername"
password:@"mypass" 
port:465 
useTLS:YES 
useAuth:YES];

I get 'Unexpected error code'. 

Logging doesn't seem to give any good hint. 
I've also tried it with different combinations below but none works. 

1) username with full email address, and with just the username before @yahoo.com
2) with and without useTLS
3) with and without useAuth
4) port 587

> > > > > > > send >>>>>>

15 UID STORE 5 FLAGS.SILENT (\Seen)

> > > > > > > end send >>>>>>

<<<<<<< read <<<<<<

15 OK UID STORE completed

<<<<<<< end read <<<<<<

> > > > > > > send >>>>>>

16 CHECK

> > > > > > > end send >>>>>>

<<<<<<< read <<<<<<

16 OK CHECK completed

<<<<<<< end read <<<<<<

**Comment by galblank** [comment]
same goes for the gmail account. crashes when TLS an Auth is On otherwise gives Unexpected error code'

**Comment by honcheng** [comment]
I think it works very well with Gmail and Google Apps Mail. 
TLS & Auth ON.

**Comment by mronge** [comment]
I can confirm it currently does not work with Yahoo. I'm working on a fix that I hope to have available soon

**Comment by honcheng** [comment]
Hi Matt,

Thanks for confirming. Think it'll be great if there's a list of what's working and what's not.

**Comment by mronge** [comment]
It now works with Yahoo SMTP

I've changed the method for sending message:

   BOOL success = [CTSMTPConnection sendMessage:testMsg 
                                                                        server:@"mail.test.com"
                                                                   username:@"test"
                                                                    password:@"test"
                                                                            port:587
                                                           connectionType:CTSMTPConnectionTypeStartTLS
                                                                      useAuth:YES
                                                                            error:&error];

For Yahoo you'll need to use the port 465 and CTSMTPConnectionTypeTLS as the connectionType

**Comment by honcheng** [comment]
Thanks. Tried it and it works!
