### ISSUE TITLE
Error Domain=mailcore Code=10 "Mailbox unavailable" UserInfo=0xb81d9c0 {NSLocalizedDescription=Mailbox unavailable}

### ISSUE THREAD

**Issue by galblank** [MailCore/MailCore#57]
I'm trying to send an smtp mail via ios simulator directly from my app 
and I get this error: Error Domain=mailcore Code=10 "Mailbox unavailable" UserInfo=0xb81d9c0 {NSLocalizedDescription=Mailbox unavailable}

When I debug it, it return error 550 at the mailesmtp_rcpt function.
Any ideas?
I'm using standard smtp with port 2525 or 25

thanks

**Comment by omolowa** [comment]
Hi,

The error 550 typically is a user unknown bounce, ie the address you used does not exist on that server.

It can happen for a number of reason, but mostly is a permanent error. If you do not have another mean to contact the recipient, you most probably have a dead address.

Check that you are using the right address on the right server, and try to mail them using another mailer software, to see if it exists.

Unless you are specifying the CTCoreAddress wrong for the recipient, I doubt this is related to MailCore.

Good luck,
Olivier./.

**Comment by galblank** [comment]
I tried testing the server and it works fine with regular SMTP servers.
here are the details:

CTCoreMessage *msg = [[CTCoreMessage alloc] init];

```
CTCoreAddress *toAddress = [[CTCoreAddress alloc] initWithName:@"Test"
```

email:@"any email will fail"];

```
[msg setTo:[NSSet setWithObject:toAddress]];

[msg setBody:@"This is a test message!"];

NSLog(@"%@",msg);

NSError *error;

BOOL success = [CTSMTPConnection sendMessage:msg server:@"smtpcorp.com"
```

username:@"username" password:@"password" port:2525 useTLS:NO useAuth:NO
error:&error];

**Comment by omolowa** [comment]
Dors it happen also if you set a from address in the MSG?

Olivier./.

**Comment by galblank** [comment]
it was an issue with the SMTP provider after all, if anyone tries to use SMTP2GO you might have issues with sending mails through this server.
FYI
