### ISSUE TITLE
Can't find MailCore.h file

### ISSUE THREAD

**Issue by galblank** [MailCore/MailCore#59]
The build goes well when I build for iOs Simulator or Device but when I try to archive it, it says that it can't find MailCore.h
I have an import <MailCore/MailCore.h> and in the Header Search Path I have like suggested her in the manual ( $(BUILT_PRODUCTS_DIR)/../../include ) but it can't find the header

**Comment by galblank** [comment]
ok, found a solution for this on my own:
For anyone who will get same errors when trying to archive an iOs app you need to add to the Header Search Path ( both Debug and Release ) the following lines : 
"$(BUILT_PRODUCTS_DIR)/../../include"
"$(BUILT_PRODUCTS_DIR)/../include"

**Comment by mronge** [comment]
## Oddly enough it works for me without the second line. Can anyone else confirm that the second include line is required?

Matt Ronge

**Comment by oddjobbodgod** [comment]
I'm still having this issue in one of my iOS projects, neither of these lines added into my Header Search Path have fixed the problem.
