### ISSUE TITLE
sendMessage timeout for poor connectivity?

### ISSUE THREAD

**Issue by rwyland** [MailCore/MailCore#65]
We are noticing some interesting problems with poor network connectivity when trying to send an SMTP Message.  It appears we are getting locked up while trying to send a message, which had us wondering if there is any sort of timeout enabled?

Our code is always checking canConnectToServer before calling sendMessage, and despite getting a green flag, still has issues sending a message.

**Comment by mronge** [comment]
Hi!

The timeout in MailCore and libetpan is set pretty high, this is most likely the problem.

Here is some sample code that shows how to set the timeout

```
#import <libetpan/libetpan.h>

// Turn network timeout down to 15 seconds
struct timeval delay = {  15, 0 };
mailstream_network_delay = delay;
```

**Comment by rwyland** [comment]
Thanks @mronge, but we ended up switching over to AWS SES
