### ISSUE TITLE
Error Domain=mailcore Code=25 "List command error" UserInfo=0xeee1810 {NSLocalizedDescription=List command error};

### ISSUE THREAD

**Issue by jobsLee-lcj** [MailCore/MailCore#73]
When I move or copy a mail to another folder,I do this : 
    BOOL success=[thisFolder moveMessageWithUID:uid toPath:@"已删除"];
    if(!success)
    {
      NSLog(@"error :",thisFolder.lastError); 
    }
or [copyMessageWithUID:uid toPath:@"已删除"]
It logged:the error as the title.
Note:the parameter for toPath is a  chinese string.
Could anyone help me~

**Comment by wongk** [comment]
Neither of those methods is properly converting the UTF8 string to modified
UTF7 used for mailbox names.

-Kris

On Thu, Feb 21, 2013 at 1:00 AM, lichuanjun notifications@github.comwrote:

> When I move or copy a mail to another folder,I do this :
> BOOL success=[thisFolder moveMessageWithUID:uid toPath:@"ÒÑÉ¾³ý"];
> if(!success)
> {
> NSLog(@"error :",thisFolder.lastError);
> }
> or [copyMessageWithUID:uid toPath:@"ÒÑÉ¾³ý"]
> It logged:the error as the title.
> Note:the parameter for toPath is a chinese string.
> Could anyone help me~
> 
> ¡ª
> Reply to this email directly or view it on GitHubhttps://github.com/mronge/MailCore/issues/73.

## 

P.S. - I'm using Taskbox to help me keep track of important emails and
action items. You can check it out in the iTunes store here: Taskbox - Mail
on iTuneshttp://ad.flurry.com/channels/serialized/CZDbVJhl9sm72bBepla_0q914wHrDm-B2krNaaQ_1TN-V5uCYdgqqzIwNtLGwLAbLXLBjfvtU2FEjK1hPkW8WYrGhVmz7RPXmxC8wo2tob9ZgAJLF3XoFD3QLoplD-R7gwGyM_-U-pDHmA5cxKPGPg

**Comment by jobsLee-lcj** [comment]
hi,wongk.thank you for your answer.However,when I use other methods such as :folder=[account folderWithPath:path],the 'path' also is a chinese string.It works well.More,the source code of
 -(BOOL)moveMessageWithUID:(NSUInteger)uid toPath:(NSStrinf *)path
{
   /...
  const char *mbPath=[path cStringUsingEncoding:NSUTF8StringEncoding];
 /...
}
What does this mean?And  How can I solve this problem?

**Comment by wongk** [comment]
The methods on CTCoreAccount are using the correct conversion. To see the
difference, compare the implementation of a method that works to one that
doesn't.

As for how you can solve the problem - create a fork, fix the issue, and
submit a pull request. Or wait for someone else to do so.

-Kris

On Thu, Feb 21, 2013 at 8:03 PM, lichuanjun notifications@github.comwrote:

> hi,wongk.thank you for your answer.However,when I use other methods such
> as :folder=[account folderWithPath:path],the 'path' also is a chinese
> string.It works well.More,the source code of
> -(BOOL)moveMessageWithUID:(NSUInteger)uid toPath:(NSStrinf *)path
> {
> /...
> const char *mbPath=[path cStringUsingEncoding:NSUTF8StringEncoding];
> /...
> }
> What does this mean?And How can I solve this problem?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mronge/MailCore/issues/73#issuecomment-13924812.

## 

P.S. - I'm using Taskbox to help me keep track of important emails and
action items. You can check it out in the iTunes store here: Taskbox - Mail
on iTuneshttp://ad.flurry.com/channels/serialized/CZDbVJhl9sm72bBepla_0q914wHrDm-B2krNaaQ_1TN-V5uCYdgqqzIwNtLGwLAbLXLBjfvtU2FEjK1hPkW8WYrGhVmz7RPXmxC8wo2tob9ZgAJLF3XoFD3QLoplD-R7gwGyM_-U-pDHmA5cxKPGPg

**Comment by jobsLee-lcj** [comment]
Hi,wongk,thank you very much.According to your suggestion,I have solve my problem.just add: [self getUTF7String:mbPath fromString:path] into the methods of moveMessageWithUID:toPath: and copyMessageWithUID:toPath:,in purpose of convert the string into UTF7String.thanks again.
