### ISSUE TITLE
oAuth 2.0 with MailCore?

### ISSUE THREAD

**Issue by Shasoosh** [MailCore/MailCore#74]
Is there a way I can use the token given by oAuth & gmail and MailCore?
Thanks

**Comment by wongk** [comment]
That requires an XOAUTH2 plugin for Cyrus SASL. The short answer is that
it's possible, but it's a fair amount of work to get up and running.

On Tue, Feb 26, 2013 at 5:47 AM, Shasoosh notifications@github.com wrote:

> Is there a way I can use the token given by oAuth & gmail and MailCore?
> Thanks
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mronge/MailCore/issues/74
> .

## 

P.S. - I'm using Taskbox to help me keep track of important emails and
action items. You can check it out in the iTunes store here: Taskbox - Mail
on iTuneshttp://ad.flurry.com/channels/serialized/CZDbVJhl9sm72bBepla_0q914wHrDm-B2krNaaQ_1TN-V5uCYdgqqzIwNtLGwLAbLXLBjfvtU2FEjK1hPkW8WYrGhVmz7RPXmxC8wo2tob9ZgAJLF3XoFD3QLoplD-R7gwGyM_-U-pDHmA5cxKPGPg

**Comment by Shasoosh** [comment]
Isn't it strange that that there isn't even one IMAP library written in objective-c that supports XOAUTH2? 
Another question, is it possible that any login methods to Gmail besides XOAUTH2 will be soon deprecated?

**Comment by mronge** [comment]
I doubt Google would remove the other login methods.

## XOAUTH2 support would be awesome to have. Pull requests welcome :)

Matt Ronge

**Comment by Shasoosh** [comment]
Pull request here or on Cyrus rep? I'd be happy to do a pull request there if you'll point me to the right direction.(couldn't find the right git)

**Comment by Shasoosh** [comment]
I don't know what's the login method MailCore IMAP is using but thought I'd let you guy know:

"We are also announcing the deprecation of older authentication mechanisms. If you’re using these you should move to the new OAuth 2.0 APIs.
We are deprecating XOAUTH for IMAP/SMTP, as it uses OAuth 1.0a, which was previously deprecated. Gmail will continue to support XOAUTH until OAuth 1.0a is shut down, at which time support will be discontinued.
We are also deprecating X-GOOGLE-TOKEN and SASL PLAIN for XMPP, as they either accept passwords or rely on the previously deprecated ClientLogin. These mechanisms will continue to be supported until ClientLogin is shut down, at which time support for both will be discontinued."

Fond here: http://googledevelopers.blogspot.co.il/2012/09/adding-oauth-20-support-for-imapsmtp.html
