### ISSUE TITLE
'libetpan/libetpan.h' file not found

### ISSUE THREAD

**Issue by danteodin** [MailCore/MailCore#75]
Downloaded all source from here, when i compile example ->IOS ->MessageSender proj i get this error :

/Users/dan/Desktop/MailCore-master/Source/CTMIME.h:33:9: 'libetpan/libetpan.h' file not found

There are not blankspace in the directry but myy libetpan folder is empty (should it be ?).

Im on it now since 5 hours any help would be much appreciated.

**Comment by mronge** [comment]
It shouldn't be empty. You probably forgot to pull down the submodules.

## Try running this command in the MailCore folder: git submodule update --init --recursive

Matt Ronge
