### ISSUE TITLE
Can not show the inline image

### ISSUE THREAD

**Issue by jobsLee-lcj** [MailCore/MailCore#79]
Hi,I recived a mail with IMAP folder,this mail has some images inline .When I show the mail use a UIWebView,like this :[webView loadHTMLString:msg.htmlBody baseURL:nil],it can show the text part ,but  the image just a frame and its alt name.What is the problem?Is this version donot support inline image?because I see this "For JPEG's We are ignoring the Content-Disposition:inline;not sure if we should be doing this?" in CTMIMETests.m. If this is the reason that I cannot show the image ,I Strongly recommended that we should do it.

**Comment by Shasoosh** [comment]
I'm having the same problem.

**Comment by jobsLee-lcj** [comment]
Hi,Shasoosh.I found a solution,you should retrive the content of the image which encoding on base64 and the content -ID,they are included in rfc822.The struct like this : 
Content--Type:image/jpeg;
     name="image003.jpg"
Content-Transfer-Encoding:base64
Content-ID:image003.jpg@.....

9j4A.....

I recommend you have a look at the doc of rfc822.

**Comment by mronge** [comment]
This RFC should be helpful http://tools.ietf.org/html/rfc2392
