### ISSUE TITLE
How can I parse a .p7m packbag and send a encrypted mail

### ISSUE THREAD

**Issue by jobsLee-lcj** [MailCore/MailCore#81]
As the title ,I want to send a mail which could be encrypted,in other words,How can I build a .p7m packbag with recipient's publicKey(certificate).And also I want to parse a mail which is encrypted by my publicKey use my privateKey.How can I do those?Is somewhere some examples?thanks~~

**Comment by JanC** [comment]
Hi,
I think S/MIME stuff is a bit outside of the scope the MailCore. MailCore can give you the `CTMIME_SinglePart` that contains your .p7m file and then it's up to you to implement the logic to encrypt/decrypt it.

Apple has a  [CMS API](http://developer.apple.com/library/mac/#documentation/Security/Reference/CryptoMessageRef/Reference/reference.html) but it is unfortunately not available on iOS. 

In my case, I used OpenSSL to implement my S/MIME operations. OpenSSL for iOS is provided in [iOSPorts](https://github.com/mronge/iOSPorts.git) that MailCore already uses.

**Comment by jobsLee-lcj** [comment]
Hi,JanC.Thank you very much for your answer. I know that CTMIME_SinglePart will deal a encrypted mail as .p7m attachment.I have also try Openssl to decrypt a  mail,It works well on PC.
As we know ,MailCore is based on libeptan,I look up into the source code of libeptan and found some files likes:mailprivacy_smime.c etc.what this mean?the libeptan support the smime?
Another question,thanks,because there is no others to respond me.As I mentioned on issues #79 ,how to show a inline image use UIWebView.Now ,I can retrive the inline image data from rfc822 which is encoded on base64 or from the mime.data which is NSData.

**Comment by JanC** [comment]
I also saw some references to pgp / smime in the libetpan but since I already had my own crypto library, I haven't investigated further. I just know that MailCore does not offer any of those in objc.

**Comment by mronge** [comment]
Working with crypto is outside the scope of MailCore. libetpan does have some smime support but I've never worked with it. I recommend asking about it on the libetpan mailing list.

Thanks.
