### ISSUE TITLE
totalMessageCount: and unreadMessageCount: usage

### ISSUE THREAD

**Issue by raneri** [MailCore/MailCore#83]
Hello, I don't understand how to use these two methods:
- (BOOL)totalMessageCount:(NSUInteger *)totalCount;
- (BOOL)unreadMessageCount:(NSUInteger *)unseenCount;

They return BOOL and expect a NSUInteger as argument, but I'm expecting them to RETURN the count of messages in the folder, can you explain the logic between this?

I've tried to do:
        [inbox totalMessageCount:nil];
where inbox is CTCoreFolder that I got with folderWithPath:

But I receive a EXC_BAD_ACCESS from the method, on line:
        *totalCount =  [self imapSession]->imap_selection_info->sel_exists;

**Comment by gmaletic** [comment]
I misread this too, the first time I saw it. The methods don't take
NSUInteger arguments: they take pointers to NSUIntegers. So here's what you
should do:

NSUInteger totalCount = 0;
BOOL success = [myFolder totalMessageCount:&totalCount];

...then totalCount will hold the value you're looking for.

**Comment by raneri** [comment]
@gmaletic Thank you very much, it works!!!!

I think it would be better to fix the comments inside CTCoreFolder.h -- it currently says:
-- Returns the number of messages in the folder.
And:
-- @return Return YES on success, NO on error.
It is a little ambiguous.

**Comment by jobsLee-lcj** [comment]
hah,it is a point parameter.you should pass a &totalCount.
