### ISSUE TITLE
'MailCore/MailCore.h' file not found

### ISSUE THREAD

**Issue by Daesuk** [MailCore/MailCore#94]
I have Xcode version 4.6.1 (on Mountain Lion).

It seems like both my project (I've followed the instruction on how to add MailCore as subproject, and setting build phases) and the example project MessageSender/InboxLister are having the same problem.

The exact error message is 

Lexical or Preprocessor Issue
'MailCore/MailCore.h" file not found

Thanks!

**Comment by Daesuk** [comment]
Yes, I am building a Mac application.

**Comment by mronge** [comment]
Make sure that there isn't a space in the path leading up to your project. Libetpan can't handles spaces in the path, so something like "/Users/username/Mail Project/MailCore" won't work because of the space.

**Comment by Daesuk** [comment]
actually there is no space. /Users/Daesuk/Documents/Sandbox/Tools/AmazonXTupleLinker/MailCore

**Comment by Daesuk** [comment]
I am going to have to say https://github.com/mronge/MailCore/issues/19 is the only solution for me.
Thanks anyways.
