### ISSUE TITLE
AOL mail - works with IMAP, but not with SMTP

### ISSUE THREAD

**Issue by honcheng** [MailCore/MailCore#97]
Anyone figured out a way to send mail with AOL?
Is it not supported yet, or I'm not using the correct settings?

**Comment by mronge** [comment]
It should work, what settings are you using?

**Comment by honcheng** [comment]
Hi,

I'm using port 587, CTSMTPConnectionTypePlain (but I've tried CTSMTPConnectionTypeStartTLS and CTSMTPConnectionTypeTLS as well), use auth, smtp.aol.com 

Here's the log from MailCore. Am I using the wrong setting? 

<<<<<<< read <<<<<<

220-mtaout-ma02.r1000.mx.aol.com ESMTP MUA/Third Party Client Interface
220-AOL and its affiliated companies do not
220-authorize the use of its proprietary computers and computer
220-networks to accept, transmit, or distribute unsolicited bulk
220-e-mail sent from the internet.
220-Effective immediately:
220-AOL may no longer accept connections from IP addresses
220 which no reverse-DNS (PTR record) assigned.

<<<<<<< end read <<<<<<

> > > > > > > send >>>>>>

EHLO honcheng-z0mg.gateway.2wire.net

> > > > > > > end send >>>>>>

<<<<<<< read <<<<<<

250-mtaout-ma02.r1000.mx.aol.com
250-PIPELINING
250-SIZE 36700160
250-ETRN
250-STARTTLS
250-AUTH PLAIN XAOL-UAS-MB LOGIN
250-AUTH=PLAIN XAOL-UAS-MB LOGIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN

<<<<<<< end read <<<<<<

> > > > > > > send >>>>>>

AUTH PLAIN dGVzdG1haWxjb3JlAHRlc3RtYWlsY29yZQBTdHJvbmdQYXNzd29yZA==

> > > > > > > end send >>>>>>

<<<<<<< read <<<<<<

235 2.7.0 Authentication successful

<<<<<<< end read <<<<<<

> > > > > > > send >>>>>>

MAIL FROM:testmailcore@aol.com RET=FULL ENVID=MailCoreSMTP

> > > > > > > end send >>>>>>

<<<<<<< read <<<<<<

250 2.1.0 Ok

<<<<<<< end read <<<<<<

> > > > > > > send >>>>>>

RCPT TO:honcheng@gmail.com NOTIFY=FAILURE,DELAY

> > > > > > > end send >>>>>>

<<<<<<< read <<<<<<

250 2.1.5 Ok

<<<<<<< end read <<<<<<

> > > > > > > send >>>>>>

DATA

> > > > > > > end send >>>>>>

<<<<<<< read <<<<<<

354 End data with <CR><LF>.<CR><LF>

<<<<<<< end read <<<<<<

> > > > > > > send >>>>>>

Date: Mon, 22 Apr 2013 00:34:33 +0800
From: Aol testmailcore@aol.com
To: "honcheng@gmail.com" honcheng@gmail.com
Message-ID: etPan.51741519.643c9869.635@honcheng-z0mg.gateway.2wire.net
Subject: Test subject
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="51741519_66334873_635"

--51741519_66334873_635
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

Test Body 
--51741519_66334873_635
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

<html>
    <head>
        <meta http-equiv=3D=22content-type=22 content=3D=22text/html; charset=3D=
utf-8=22 />
    </head>
    <body dir=3D=22auto=22>
        <div>Test Body </div>
        =09
    </body>
</html>
--51741519_66334873_635--

.

> > > > > > > end send >>>>>>

<<<<<<< read <<<<<<

521 5.2.1   521 AOL will not accept delivery of this message 

<<<<<<< end read <<<<<<

> > > > > > > send >>>>>>

QUIT

> > > > > > > end send >>>>>>

**Comment by honcheng** [comment]
Oops. It works.
I only get the error above if CTCoreAddress name starts with 'AOL'. Must've been a behaviour of their server to reject this.
